title: Jaehyeon Park
description: >-
  Jaehyeon Park is a data science student and researcher working in
  statistical modeling, sports analytics, and computational linguistics.
url: https://wogus00.github.io
baseurl: ""
timezone: Asia/Seoul
author:
  name: Jaehyeon Park
  email: jp4880@columbia.edu
  linkedin: https://linkedin.com/in/jaehyeon-park-38238a180
  github: https://github.com/wogus00

markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:title/

defaults:
  - scope:
      path: blog/en/_posts
      type: posts
    values:
      layout: post
      lang: en
  - scope:
      path: blog/ko/_posts
      type: posts
    values:
      layout: post
      lang: ko

exclude:
  - README.md
  - README.local.md
  - Gemfile
  - Gemfile.lock
  - vendor
