baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'wogus'

[params]
defaultTheme = "auto"

[params.profileMode]
enabled = true
title = "Jaehyeon Park"
subtitle = "This is subtitle"
imageUrl = "<image link>"
imageTitle = "<title of image as alt>"
imageWidth = 120
imageHeight = 120

  [[params.profileMode.buttons]]
  name = "Archive"
  url = "/archive"

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/"

[[params.socialIcons]]
name = "<platform>"
url = "<link>"

[[params.socialIcons]]
name = "<platform 2>"
url = "<link2>"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
